# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 811abbc8198733b0ba3fbdefef2b1c72bff1e80bb407f62569ac1d410ab9912622861e85f7b4733c89a202e69224dbac486098375d1a4c56f64ba90d003fb72b

test:
  secret_key_base: 3a17d632d614356cda9e52f99305a6c65d3a12143645c133d0209e6dde456fa9c597c3c2f31fd13d431be71f9d230f14fa0b0d947920e4bb2ab40b3bc2dee2e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
