# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39208d0046be92deb55a7ce5d48f50225e958fa1dfba7214a37f0e95eae130feb2f277af2fab681738cbb12b5d57c6cbb92ca7329d449fcfb3f1379495974345

test:
  secret_key_base: c730b78d1057e803902e110425c3d61b7dde34a5b9b6eb1fddf7f008873276c5577752fa54fe1084dce4146c1e6609e82b8f493c08292499e5ee7a75914bbc6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
