# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c14f5e45ffb3e8d599c028c018cf9763d8f8d1d1a65f72b6113a47ace1bf014f15a9ad3d1f8c5953d7578f3c0e3b539ca6e15e84c52fe92371f7c06bc62a9d01

test:
  secret_key_base: cddb72f6662daff7f2a60e083226cb0e3e5c13b73051a8ee1982d80ed4880c0afdefb8991c2eff55c063d5d44649a436ce2de9a4e535248dff36572a4d206003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
