# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fff3806a304654a3850cdd2cff96956feb2dc76b7bc84dbfc4da5a4a55916c5a8ad5e44c81d437134210dbbb22cf0120977d80e64cff029e410a65227f03f4f4

test:
  secret_key_base: 50d1b2d3541a6d116c06fb3d39d9ef63526a908c95d416f2c4f3a096ebffd97280203ae88eaf4ee183edcaf878c31242b27564ca6bd8425f333aa4f3b27dbdf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
